//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuakeMapFast.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuakeMapFast.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ※このファイルは更新確認にも使用しています。
        ///
        ///
        ///ここのフォルダの&quot;user.config&quot;はソフトの設定の一次保存です。実行ファイルと同じ場所にも保存されます。(&quot;UserSetting.xml&quot;)
        ///
        ///実行ファイルの場所を変えるか更新すると別の場所に新しく保存されます。
        ///例えば&quot;...\AppData\Local\Ichihai1415\QuakeMapFast.exe_Url_4tliypkkuk2tnq0h0u0kv2ufqonh5203\0.1.0.0\user.config&quot;の場合、&quot;QuakeMapFast.exe_Url_4tliypkkuk2tnq0h0u0kv2ufqonh5203&quot;の部分は実行ファイルのパスによって変わり、&quot;0.1.0.0&quot;がバージョンによって変わります。
        ///実行ファイルと同じフォルダの&quot;AppDataPath.txt&quot;というファイルにその実行ファイルで使用しているファイルのパスが記載されているので、これ以外のものは削除できます。ソフトをもう利用しない場合はこれも削除できます。このファイルを削除した状態で起動すると設定の初期化が行われます。
        ///
        ///ソフトの起動時 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppData_README {
            get {
                return ResourceManager.GetString("AppData_README", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;type&quot;:&quot;FeatureCollection&quot;, &quot;features&quot;: [
        ///{&quot;type&quot;:&quot;Feature&quot;,&quot;geometry&quot;:{&quot;type&quot;:&quot;Polygon&quot;,&quot;coordinates&quot;:[[[141.49062527873366,43.68444110807076],[141.4874752791609,43.684895558883],[141.47999917002574,43.68797444096771],[141.4750211149326,43.69271777480549],[141.46871167290544,43.70077944061876],[141.4645963941084,43.702354170608544],[141.46262306120536,43.701337225332736],[141.45309416316513,43.700900838303085],[141.44319972758547,43.703379720597695],[141.43883167274362,43.70382972066511],[141.439117223681 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreaForecastLocalE_GIS_20190125_1 {
            get {
                return ResourceManager.GetString("AreaForecastLocalE_GIS_20190125_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IntLegend {
            get {
                object obj = ResourceManager.GetObject("IntLegend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] JSON_sample {
            get {
                object obj = ResourceManager.GetObject("JSON_sample", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Apache License
        ///                           Version 2.0, January 2004
        ///                        http://www.apache.org/licenses/
        ///
        ///   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///   1. Definitions.
        ///
        ///      &quot;License&quot; shall mean the terms and conditions for use, reproduction,
        ///      and distribution as defined by Sections 1 through 9 of this document.
        ///
        ///      &quot;Licensor&quot; shall mean the copyright owner or entity authorized by
        ///      the copyright owner that is granting the License.
        ///
        ///      &quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Koruri_LICENSE {
            get {
                return ResourceManager.GetString("Koruri_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Koruri_Regular {
            get {
                object obj = ResourceManager.GetObject("Koruri_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   {&quot;type&quot;:&quot;FeatureCollection&quot;, &quot;features&quot;: [
        ///{&quot;type&quot;:&quot;Feature&quot;,&quot;geometry&quot;:{&quot;type&quot;:&quot;Polygon&quot;,&quot;coordinates&quot;:[[[179.99921875,-16.168554687500006],[180,-16.152929687500006],[179.5517578125,-16.24990234375001],[179.35917968750005,-16.3798828125],[179.09140625000003,-16.4375],[178.86572265625,-16.5400390625],[178.80507812500002,-16.631445312500006],[178.58359375000003,-16.621875],[178.6037109375,-16.800585937500003],[178.70664062500003,-16.976171875],[178.88369140625002,-16.886035156250003],[179.0068359375,-16.9001 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Map_world {
            get {
                return ResourceManager.GetString("Map_world", resourceCulture);
            }
        }
    }
}
